#!/usr/bin/env python3
"""Shared filesystem locations for Duckietown experiments."""

from pathlib import Path


DUCKIETOWN_ROOT = Path.home() / "duckietown"
DATA_ROOT = DUCKIETOWN_ROOT / "data"
CHECKPOINT_ROOT = DUCKIETOWN_ROOT / "checkpoints"

IMITATION_LEARNING_DATA_DIR = DATA_ROOT / "imitation_learning"
IMITATION_LEARNING_TRAIN_DATA_DIR = IMITATION_LEARNING_DATA_DIR / "train"
IMITATION_LEARNING_VAL_DATA_DIR = IMITATION_LEARNING_DATA_DIR / "val"

IMITATION_LEARNING_CHECKPOINT_DIR = CHECKPOINT_ROOT / "imitation_learning"
RL_PPO_DUCKIEMATRIX_CHECKPOINT_DIR = CHECKPOINT_ROOT / "rl_ppo_duckiematrix"
RL_PPO_GYM_DUCKIETOWN_CHECKPOINT_DIR = CHECKPOINT_ROOT / "rl_ppo_gym_duckietown"

EVALUATION_DATA_DIR = DATA_ROOT / "evaluations"
IL_GYM_DUCKIETOWN_EVALUATION_DIR = EVALUATION_DATA_DIR / "il_gym_duckietown"
RL_GYM_DUCKIETOWN_EVALUATION_DIR = EVALUATION_DATA_DIR / "rl_gym_duckietown"
EVALUATION_SCREENSHOT_DIR = EVALUATION_DATA_DIR / "screenshots"
